name: Build and Deploy to Azure Container App

on:
  push:
    branches:
      - main  # o tu rama principal
  workflow_dispatch:

env:
  REGISTRY: knoxiacr.azurecr.io
  IMAGE_NAME: knoxia-transcriptor

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container App
      uses: azure/container-apps-deploy-action@v2
      with:
        acrName: knoxiacr
        containerAppName: knoxia-function-docker
        resourceGroup: knoxia-rg
        imageToDeploy: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
