name: Trigger auto deployment for knoxia-transcriptor-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/knoxia-transcriptor-app-AutoDeployTrigger-e71a9eed-4cb3-4b75-8d3e-eecfc60b90c2.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.KNOXIATRANSCRIPTORAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.KNOXIATRANSCRIPTORAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.KNOXIATRANSCRIPTORAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.KNOXIATRANSCRIPTORAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.KNOXIATRANSCRIPTORAPP_REGISTRY_PASSWORD }}
          containerAppName: knoxia-transcriptor-app
          resourceGroup: knoxia-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


